### ISSUE TITLE
Greeting NPC

### ISSUE THREAD

**Issue by nmarshall23** [nmarshall23/necromancers-fortnight#4]
Player's spawn point is in her garden. She asks rhetorically why people keep falling from the sky here.
Raison d'etre is to explain some changes from Vanilla. Give the player direction of how to handle those changes. 

### Todo
 - [ ] Build Greeting NPC's House and Garden.
 - [ ] Save it in Recurrent Complex
 - [ ] Test that it works
 - [ ] Add NPC Greeting Dialog
 - [ ] Add NPC Quests
 - [ ] Add nearby Ruins of houses, one will contain parts of a **Cooking for Blockheads** kitchen. 

#### A Promise of Adventure
 1. [ ] Punching Trees
    -  Tell them to chop some trees.
    -  That they cut logs into planks by placing the an Iron or better axe and the log in a crafting grid.
    -  Turn in 16 Planks.

 2. [ ] Cooking Charcoal
    - Dig a Charcoal Pit.

 3. [ ] Tinkering Around
    - Build Tinker's Tools
 2. [ ] Help in the garden
    - [ ] Informs the player about **Spice of Life** that they will need to eat a variety of foods. 
    - [ ] Informs them that crops can be harvested without breaking them. Also how **Rustic** tomatoes work. 
    - [ ] Craft a **Tiny Progr** Sycal for harvesting crops.
    - [ ] Craft a watering can.
    - [ ] Turn in 8 potatos, 8 Tomatoes, and 8 Wheat.
 3. [ ] Taming of Animals
    - [ ] Informs them about **Animania**.

### About her
 - She has never traveled
 - Lived here with her Mother and Father who are now, passed on. ( should their graves be nearby? )
 - Not sure why no monsters will come near here. But there are monster underground.
 - Heard long ago there was a great Dwarven kingdom. Her mother told her tales of them. Something happened to them, due to their arrogance and now all that is left is their Ancient Golems now run amouk.
 - Heard of Testificate Villagers but never seen one, no idea why they abandoned any nearby Villages. 
 - Has no knowledge of the Necromancer or his curse.
 - There is a group of Knights? ( What to call them? ) that keep a camp somewhere not far that check in on her.
 - There is a Old lady not far that also lives not far, she's an odd one. Thinks she might be a witch but are there good witches?
